### ISSUE TITLE
Feature request: add config option to display the date in other language

### ISSUE THREAD

**Issue by eclipseo** [jsynowiec/vscode-insertdatestring#10]
Sometimes I'd like to display the date in French, sometimes in English. It would be nice to support this in options.

**Comment by jsynowiec** [comment]
I think it's a good idea to explore, but because I don't use dates in other languages, I'll leave it here for others to pick and send a PR.

**Comment by rioj7** [comment]
@eclipseo  You could have a look at [Command Variable](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable) v0.10.0 and use the `extension.commandvariable.dateTime` that uses Locales to format date and time and configuration of how each field is generated.

--
**Maintainer update:** @rioj7 is author of linked extension, so this post can be classified as a self promition.

**Comment by jsynowiec** [comment]
I am going to close this due to the lack of activity.

**Comment by rioj7** [comment]
Not self promotion, I waited 3 years for a solution and it still is not fixed in this extension
