### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by m2i7c9k** [jsynowiec/vscode-insertdatestring#11]
I want to ask if you'll support the latest ver. of VS?

**Comment by jsynowiec** [comment]
Not sure what do you mean by that? I have the latest stable version of vscode (1.33.1) and the extension installs and works just fine.

**Comment by m2i7c9k** [comment]
I can't install it for VS 2019.

![image](https://user-images.githubusercontent.com/46530426/57586690-d6be8680-74f9-11e9-8198-8e9dd80568e3.png)

log file:
12.05.2019 21:05:34 - Microsoft VSIX Installer
12.05.2019 21:05:34 - -------------------------------------------
12.05.2019 21:05:34 - vsixinstaller.exe version:
12.05.2019 21:05:34 - 16.1.1080
12.05.2019 21:05:34 - -------------------------------------------
12.05.2019 21:05:34 - Command line parameters:
12.05.2019 21:05:34 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,d:\Downloads\jsynowiec.vscode-insertdatestring-2.2.4.vsix
12.05.2019 21:05:34 - -------------------------------------------
12.05.2019 21:05:34 - Microsoft VSIX Installer
12.05.2019 21:05:34 - -------------------------------------------
12.05.2019 21:05:41 - Initializing Install...
12.05.2019 21:05:41 - Extension Details...
12.05.2019 21:05:41 - 	Identifier         : vscode-insertdatestring
12.05.2019 21:05:41 - 	Name               : Insert Date String
12.05.2019 21:05:41 - 	Author             : jsynowiec
12.05.2019 21:05:41 - 	Version            : 2.2.4
12.05.2019 21:05:41 - 	Description        : Insert the current date and time according to configured format.
12.05.2019 21:05:41 - 	Locale             : en-US
12.05.2019 21:05:41 - 	MoreInfoURL        : 
12.05.2019 21:05:41 - 	InstalledByMSI     : False
12.05.2019 21:05:41 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12.05.2019 21:05:41 - 
12.05.2019 21:05:41 - 	SignatureState     : Unsigned
12.05.2019 21:05:41 - 	Supported Products : 
12.05.2019 21:05:41 - 		Microsoft.VisualStudio.Code
12.05.2019 21:05:41 - 			Version : 
12.05.2019 21:05:41 - 
12.05.2019 21:05:41 - 	References         : 
12.05.2019 21:05:41 - Signature Details...
12.05.2019 21:05:41 - 	Extension is not signed.
12.05.2019 21:05:41 - 
12.05.2019 21:05:41 - Searching for applicable products...
12.05.2019 21:05:41 - Found installed product - Global Location
12.05.2019 21:05:41 - Found installed product - ssms
12.05.2019 21:05:41 - Found installed product - Visual Studio Community 2019
12.05.2019 21:05:41 - Found installed product - Visual Studio Community 2017
12.05.2019 21:05:41 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by jsynowiec** [comment]
This is an extension for **Visual Studio Code**. The installer tells you exactly that. I don't plan nor considered supporting the regular Visual Studio.

**Comment by m2i7c9k** [comment]
I installed another extension, and then your extension installed correctly - that's weird, but it's working now :) So, thank you

**Comment by m2i7c9k** [comment]
OK, I got it it's for Visual Studio Code :) so the question is updated: Ic could be rewritten for Visual Studio 2019?
So I can add datetime to head of (sub/function) my code like:

Sub Name
'date time

... code

End Sub

Thanks.

P.S. I can pay for it :)
