### ISSUE TITLE
TZ problem

### ISSUE THREAD

**Issue by hsmyers** [jsynowiec/vscode-insertdatestring#12]
The extension is off-by-one in showing time on my machine. I live in a Mountain Daylight Savings zone, GMT-06 while you display -0700. My system variable is:

```
c:\>set TZ
tz=UTC-6
```

**Comment by jsynowiec** [comment]
This extension is using whatever time zone is available to the Node.js runtime, so effectively what's set on the host OS. I don't see how it could be off by an hour only on your computer (other than a problem with your OS configuration)

**Comment by hsmyers** [comment]
I thought that might be the case. I wonder about just that, the OS making
the mistake. In any event, it isn't you or anyone else other than the OS so
I'll begin to play around with the TZ settings and see what happens. Thanks
for your attention, keep up the good work!

**Comment by hsmyers** [comment]
Found it! TZ=UTC-6 gives off by one error as mentioned. On the other hand
TZ="Mountain Daylight Time" provides correct time all around.

**Comment by jsynowiec** [comment]
I think that you should set the `TZ` env var to a proper [TZ name like](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) `Canada/Mountain`, rather than the `Mountain Daylight Time`.

Glad you sorted it out. Closing.
