### ISSUE TITLE
add a custom rule command? -- Insert DateTime with custom rule

### ISSUE THREAD

**Issue by xianghongai** [jsynowiec/vscode-insertdatestring#13]
Insert DateTime with custom rule:

The format `YYYY-MM-DD-hh:mm:ss` is required, and at the same time, the format `-YYYYMMDD-hhmmss` is required, so need a custom rule. :)

**Comment by jsynowiec** [comment]
You can use

> Insert Formatted DateTime (`⇧+⌘+⌥+I` on OS X, `Ctrl+Alt+Shift+I` on Windows and Linux) - Prompt user for format and insert formatted date and/or time at the cursor position.

to insert custom, ad hoc formats.

**Comment by xianghongai** [comment]
`insert formatted datetime` is perfect if it remembers the last format.
