### ISSUE TITLE
Help: how to make AM/PM lowercase?

### ISSUE THREAD

**Issue by agmemon10** [jsynowiec/vscode-insertdatestring#14]
right now, when I input "A" into format, it defaults the Ante meridiem (AM) and Post meridiem (PM) to uppercase. Is there anyway to have it as lowercase? I tried using "a" but that does not work for me

This is the format I am currently using: YYYY-MM-DD HH:mmA

**Comment by jsynowiec** [comment]
Unfortunately no. It'll be always upper-case. But I'm going to rework the date parsing and formatting at some point to allow much more customisation and formats.

**Comment by agmemon10** [comment]
Okay, thank you
