### ISSUE TITLE
Insert UnixTimestamp (in seconds)

### ISSUE THREAD

**Issue by MrVauxs** [jsynowiec/vscode-insertdatestring#16]
A quick suggestion to add an option to insert the amount of **seconds** since Jan 01 1970, rather than milliseconds.

**Comment by jsynowiec** [comment]
@MrVauxs You can use custom format to do that. Use the "Insert Formatted DateTime" action and type `u` as a format.

**Comment by jsynowiec** [comment]
Closing as stale.
