### ISSUE TITLE
`TZD` is no longer a valid format placeholder

### ISSUE THREAD

**Issue by trongthanh** [jsynowiec/vscode-insertdatestring#2]
Extension version 1.1.2.
 
Tried this format:
```json
{ "insertdatestring.format": "YYYY-MM-DDThh:mm:ssTZD" }
```
And it turns out: `2017-02-03T13:25:19T+073`. (the last D is considered date of month)

I noticed that you changed the date formatter to `date-format-lite` package, and its time zone designator is __Z__. So documentation should follow. 

Besides, the date formatter also support `iso` as format settings which output the ISO date time format at GMT. I think for convenience sake, this should be noted down in documentation as well.

**Comment by jsynowiec** [comment]
Thanks for reporting.
