### ISSUE TITLE
Feature Request: recent formats or predefined list in "Insert Formatted DateTime"

### ISSUE THREAD

**Issue by hukadev** [jsynowiec/vscode-insertdatestring#20]
Hi there,

Thanks for your great extension.

I have a use case like this, could you please consider it?
My use case is in some file, I need to write YYYY-MM-DD hh:mm:ss and YYYYMMDDhhmmss
But I have to modify the formats each time.

My idea is to add an array of formats in the config, so we can select it in prompt.

Best regards,
Huka

**Comment by hsmyers** [comment]
I would second this, but as long as I'm wishing, I'd add the ability to set the default out of the list…

**Comment by jsynowiec** [comment]
I am going to close this due to the lack of activity.
