### ISSUE TITLE
Publish to open-vsx.org?

### ISSUE THREAD

**Issue by hl2guide** [jsynowiec/vscode-insertdatestring#21]
Please consider publishing this extension to: https://open-vsx.org/

So that users of VSCodium can use it too.

**Comment by brackenhill-mob** [comment]
+1

But a workaround is to download the extension and then side load it in VSCodium or whatever.

**Comment by eabase** [comment]
@brackenhill-mob How do you do that?

**Comment by brackenhill-mob** [comment]
@eabase I gave up on VSCodium shortly after I posted here so I'm doing this from memory but you download the plugin and put it in the VSCodium plugin folder. I'm a Linux user so this is under ~/.config but if you use Windows you'll have to search for it as I've no idea

A quick search threw up this which might be helpful
https://www.codegrepper.com/code-examples/whatever/how+to+can+i+install+vscode+extension+on+vs+codium

**Comment by jsynowiec** [comment]
I do not use Open VSX, so I am not interested in supporting it. There are many ways to install the extension in VSCodium, for example, how @brackenhill-mob described it.
