### ISSUE TITLE
Insert date with Z difference, format wrong

### ISSUE THREAD

**Issue by therealmarv** [jsynowiec/vscode-insertdatestring#3]
Hi,
I'm currently in the Philippines with a Mac (German language). My configuration:

OS: macOS 10.12.3
VSCode: 1.9.1
vscode-insertdatestring: 1.2.0

In my settings.json I put:
```
"insertdatestring.format": "YYYY-MM-DDThh:mm:ssZ"
```

Executed Insert Datetime

Expected I see
```
2017-02-10T17:56:00+08:00
```

but I got this output:
```
2017-02-10T17:56:00+08
```

Personal note: thanks for this plugin. Very useful for inserting timestamps into some Markdown files :) 👍

**Comment by jsynowiec** [comment]
Thanks for reporting. I'll look into this.

**Comment by jsynowiec** [comment]
Please update the extension to **1.2.1** and use the following format: `YYYY-MM-DDThh:mm:ssZZZ`

**Comment by therealmarv** [comment]
I confirm, works now! Thanks!
