### ISSUE TITLE
Run it on save instead of manually

### ISSUE THREAD

**Issue by rbfonbuena** [jsynowiec/vscode-insertdatestring#5]
Can this be integrated to something like a script that will automatically run it on an onSave event, instead of manually?

I'm new to VSCode and currently using Sublime where I have a python script that replaces a tag you place anywhere in your file, i.e. {@timestamp}, which is replaced by a date stamp or updates it if it exists whenever the file is saved.

Was wondering if this is possible on VSC using your extension.

**Comment by jsynowiec** [comment]
Since vscode 1.20 you can now use some new snippet variables. Please see [release notes](https://code.visualstudio.com/updates/v1_20#_more-snippet-variables). Unfortunately there is not _timestamp_ variable, but you can compose a formatted date instead.
