### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by ghedeonn** [jsynowiec/vscode-insertdatestring#6]
Thank you for the extension! You did a great job, simple and fast.

One thing i notice to be wrong, for the `Insert Formated DateTime` command when choosing 'u' we get back the seconds format but when we choose 'U' we get the milliseconds format. But in the documentation we have the following: 
u - Milliseconds since the Unix Epoch (January 1 1970 00:00:00 GMT)
U - Seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)

which is exactly opposite of what we get from the extension. Now i dont know if the docs are wrong or the extension but they should do the same thing.

Thanks.

**Comment by jsynowiec** [comment]
Thanks for reporting. You're right. I've fixed the typo in the readme.
