### ISSUE TITLE
Manual Installation Error

### ISSUE THREAD

**Issue by Xyc0** [jsynowiec/vscode-insertdatestring#8]
Manually installing package to `~/.vscode/extensions` produces the following error when `Insert DateTime` is invoked.

```
command 'insertDateString.insertDateTime' not found
```

vscode v1.25.1 win64
commit 1f12e67

**Comment by jsynowiec** [comment]
Can you describes steps how you perform the manual installation? Are you using the `vsix` package downloaded from the marketplace and `Install from VSIX` command?

**Comment by Xyc0** [comment]
Is there a VSIX published for the extension?

**Comment by jsynowiec** [comment]
To download an extension, navigate to the details page within the Marketplace. On that page, there is a Download Extension link in the Resources section which is located on the right hand side of the page.

**Comment by Xyc0** [comment]
https://marketplace.visualstudio.com/items?itemName=jsynowiec.vscode-insertdatestring

![untitled](https://user-images.githubusercontent.com/470296/42847480-1e3180b8-89ea-11e8-8d0f-9c2019d39286.png)

**Comment by jsynowiec** [comment]
<img width="319" alt="obraz" src="https://user-images.githubusercontent.com/1029142/42847527-9c91eb28-8a1c-11e8-8b5c-42fe4fbefef5.png">

Works for me.

**Comment by Xyc0** [comment]
oooooo, i had to change my user agent to internet explorer for microsoft to serve me the link.
that's not cool...
sorry to bother you.
