### ISSUE TITLE
Feature Request: the timezone abbreviation

### ISSUE THREAD

**Issue by eclipseo** [jsynowiec/vscode-insertdatestring#9]
I'd like to display the timezone using abbreviation like CET GMT PST and so on. I didn't not find any docs to do that. Could you implement it?

**Comment by jsynowiec** [comment]
Related to #10 in some way. Might do both at some point, but it'll be a breaking change.

**Comment by jsynowiec** [comment]
I am going to close this due to the lack of activity.
